version: 3
workdir: internal
allow:
  depOnAnyVendor: false
  deepScan: true
  ignoreNotFoundComponents: false

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*/test/.*$"
  - "^.*/shared/bootstrap/.*$"
  - "^.*/shared/server/.*$"
  - "^.*/shared/infrastructure/persistence/migrations/.*$"

vendors:
  mongodb-driver:
    in:
      - "go.mongodb.org/mongo-driver"
      - "go.mongodb.org/mongo-driver/**"
  fiber:
    in:
      - "github.com/gofiber/fiber/v3"
      - "github.com/gofiber/fiber/v3/**"
      - "github.com/gofiber/contrib/v3/**"
  viper:
    in:
      - "github.com/spf13/viper"
  gotenv:
    in:
      - "github.com/subosito/gotenv"
  validator:
    in:
      - "github.com/go-playground/validator/v10"
  swagger:
    in:
      - "github.com/gofiber/contrib/v3/swaggo"
      - "github.com/gofiber/contrib/v3/swaggo/**"
      - "github.com/swaggo/swag"
      - "github.com/swaggo/files/v2"
  go-pkgs-errors:
    in:
      - "github.com/gambitier/go-pkgs/errors"
      - "github.com/gambitier/go-pkgs/errors/**"
  go-pkgs-apiresponse:
    in:
      - "github.com/gambitier/go-pkgs/apiresponse"
      - "github.com/gambitier/go-pkgs/apiresponse/**"
  go-pkgs-logging:
    in:
      - "github.com/gambitier/go-pkgs/logging"
      - "github.com/gambitier/go-pkgs/logging/**"
  go-pkgs-observability:
    in:
      - "github.com/gambitier/go-pkgs/observability"
      - "github.com/gambitier/go-pkgs/observability/**"
  logrus:
    in:
      - "github.com/sirupsen/logrus"

components:
  domain:
    in: "**/domain/**"
  application:
    in: "**/application/**"
  infrastructure:
    in: "**/infrastructure/**"
  presentation:
    in: "**/presentation/**"
  config:
    in: "config/**"
  platform:
    in: "**/platform/**"

commonComponents:
  - config

commonVendors:
  - viper
  - gotenv
  - validator
  - go-pkgs-logging

deps:
  domain:
    mayDependOn:
      - domain
    canUse:
      - go-pkgs-errors

  application:
    mayDependOn:
      - domain
      - application
    canUse:
      - go-pkgs-errors

  infrastructure:
    mayDependOn:
      - domain
      - application
      - infrastructure
    canUse:
      - mongodb-driver
      - go-pkgs-errors

  presentation:
    mayDependOn:
      - domain
      - application
      - presentation
      - platform
    canUse:
      - fiber
      - swagger
      - go-pkgs-errors
      - go-pkgs-apiresponse
      - go-pkgs-logging

  platform:
    mayDependOn:
      - platform
    canUse:
      - go-pkgs-errors
      - go-pkgs-logging
      - go-pkgs-observability
      - logrus
      - fiber

  config:
    mayDependOn:
      - config
    canUse:
      - go-pkgs-logging
      - go-pkgs-observability
