server:
  environment: development
  http:
    port: 8080
  cors:
    allowOrigins: "*"
    allowCredentials: false

logging:
  service_name: golang-service-template
  level: debug
  format: json
  sinks:
    - type: console
      enabled: true

opentel:
  enabled: false
  service_name: golang-service-template
  collector_url: "localhost:4317"
  insecure: true
  sampling:
    ratio: 1.0
  resource:
    deployment_environment: development

mongo:
  uri: "mongodb://admin:password@127.0.0.1:27017/?replicaSet=rs0&authSource=admin"
  database: "golang-service-template-dev"

swagger:
  enabled: true
  username: "admin"
  password: "changeme"
